server:
  port: 8080

spring:
  application:
    name: lcdp
  redis:
    host: 127.0.0.1
    port: 16379
    password: 'rv7g2mWuetvjwbd7'
#    redisson:
#      config:
#        singleServerConfig:
#          address: "redis://127.0.0.1:16379"
#          password: 'rv7g2mWuetvjwbd7'

  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:11521/PDB1
    username: JIM
    password: 'JIM'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl