server:
  port: 7011
  servlet:
    context-path: /cyder

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(beP09vEROJfvNCN7KVwZS6EAuCtcG2XqS9phC3C/cgUq93iuxpXlRr4cU/oJ1LBR)
    password: ENC(glirxHjw+WloN0azcwyyBSpSBFM1YsqH0ut8HmfHOoIotuMSyhRH+KjBaHl+B9HZ)
    url: jdbc:mysql://47.103.21.83:3306/cyder?characterEncoding=utf-8
  data:
    redis:
      host: 47.103.21.83
      port: 6379
      password: ENC(TwpaO4JW07OBxrxkqw3URlNC4iyroqGAEihAuTgKNhOpY/y3deHNBiqPzPlApswXwtZ5KR/NwoqWc+ns240hgQ==)

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteStatus
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:cn/datawisher/cyder/**/mapper/xml/*.xml


jasypt:
  encryptor:
    password: ${jasyptp}
    bootstrap: true

tushare:
  api:
    url: http://api.tushare.pro
    token: 1e418e986f53e167cb87356df55890da37ff19eef28ff396668f6eb9
