server:
  port: 7011
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cyder?characterEncoding=utf-8

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteStatus
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:cn/datawisher/cyder/**/mapper/xml/*.xml

tushare:
  api:
    url: http://api.tushare.pro
    token: 1e418e986f53e167cb87356df55890da37ff19eef28ff396668f6eb9
