server:
  port: 8011
spring:
  application:
    name: spring-cloud-feign-consumer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true