server:
  port: 8276

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway
    username: rps
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    enabled: true
#    locations: classpath:/sql/pg
#    schemas: myschema
    locations: classpath:/sql/oracle
    schemas: youschema
    baseline-on-migrate: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
