server:
  port: 80

spring:
  application:
    name: spring-boot-jdbc
  datasource:
    url: jdbc:mysql://localhost:13306/ace?autoReconnect=true
    username: root
    password: root

logging:
  level:
    root: info
