server:
  port: 8814

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@127.0.0.1:11521/PDB1
    username: RPS
    password: 5OGU0NWRkY2I0YTk5
  jpa:
    show-sql: true
#    database: postgresql
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect