server:
  port: 9777

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.discovery.host:127.0.0.1}:8848
        namespace: ${nacos.discovery.namespace:public}
        group: ${nacos.discovery.group:DEFAULT_GROUP}
        username: ${nacos.discovery.username:nacos}
        password: ${nacos.discovery.password:nacos}
  datasource:
    url: jdbc:postgresql://localhost:15432/bee?connectTimeout=60&socketTimeout=60
    username: rps
    password: YTYyZWE3MmEyNDc5OGU0NWRkY2I0YTk5