spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/mybatis?TimeZone=Asia/Shanghai
    username: rps
    password: YTYyZWE3MmEyNDc5OGU0NWRkY2I0YTk5