spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:11521/PDB1
    username: JIM
    password: JIM

#mybatis-plus:
#  global-config:
#    db-config:
#      capital-mode: true