server:
  port: 8812

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tysql
    username: rps
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
