server:
  port: 7011

spring:
  application:
    name: bee-system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bee
    hikari:
      username: root
      password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: "i18n/messages"
    fallback-to-system-locale: false

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 2.0.0
  try-host: http://localhost:${server.port}
